### ISSUE TITLE
Travis build osx python3 fails

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/dimod#125]
https://travis-ci.org/dwavesystems/dimod/jobs/348408848
```
Error: python 2.7.14 is already installed
To upgrade to 3.6.4_3, run `brew upgrade python`
```

**Comment by arcondello** [comment]
Resolved by changing
```       
 - os: osx
          language: generic
          env: TOXENV=py36
          before_install:
            - brew update
            - brew upgrade python
            - pip install virtualenv
            - virtualenv env -p python
            - source env/bin/activate
```
